<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>TacticalDoorWedgeServer</RootNamespace>
    <AssemblyName>TacticalDoorWedgeServer</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <Version>1.0.0</Version>
    <OutputPath>bin\$(Configuration)\TacticalDoorWedgeServer\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.3" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.3" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.0.3" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.3" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

</Project>
